{{- if .Values.autoInstall.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "fullname" . }}-init
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded,hook-failed
spec:
  backoffLimit: 1
  activeDeadlineSeconds: 100
  template:
    metadata:
      name: {{ template "fullname" . }}-init
      labels:
        heritage: {{.Release.Service | quote }}
        release: {{.Release.Name | quote }}
        chart: "{{.Chart.Name}}-{{.Chart.Version}}"
    spec:
      {{- if .Values.image.pullSecrets }}
      imagePullSecrets:
      {{- range .Values.image.pullSecrets }}
        - name: {{ . }}
      {{- end }}
      {{- end }}
      restartPolicy: Never
      containers:
      - name: {{ template "fullname" . }}-init
        image: "iqualch/dc-drupal-init:latest"
        imagePullPolicy: "Always"
        env:
        - name: WEBSITE_PREFIX
          value: "{{ template "name" . }}"
        - name: MYSQL_DRUPAL_HOST
          value: {{ .Values.autoInstall.dbHost | quote }}
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.autoInstall.dbSecret | quote }}
              key: MYSQL_ROOT_PASSWORD
        ports:
        - name: http
          containerPort: 80
        tty: true
        volumeMounts:
        - mountPath: /var/repo
          name: drupal-repo
        - mountPath: /var/www
          name: drupal-data
        resources:
{{ toYaml .Values.resources | indent 10 }}
      volumes:
      - name: drupal-repo
        hostPath:
          path: {{ .Values.autoInstall.baseMount }}{{ .Values.autoInstall.source }}
          type: ""
      - name: drupal-data
        hostPath:
          path: {{ .Values.persistence.baseMount }}/www/drupal
          type: ""
    {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
      {{- end -}}
{{- end }}
