{{- if .Values.ingress.enabled }}
{{- range .Values.ingress.hosts }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "{{ .name | replace "." "-" }}-ingress"
  labels:
    app: {{ template "fullname" $ }}
    chart: "{{ $.Chart.Name }}-{{ $.Chart.Version }}"
    release: "{{ $.Release.Name }}"
    heritage: "{{ $.Release.Service }}"
  annotations:
    {{- if (and (.tls) (eq (default .tlsType "auto") "auto")) }}
    cert-manager.io/cluster-issuer: {{ $.Values.ingress.certissuer | quote }}
    {{- end }}
    {{- range $key, $value := .annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  rules:
  - host: {{ .name }}
    http:
      paths:
        - path: {{ default "" .path }}
          backend:
            serviceName: {{ template "fullname" $ }}
            servicePort: 80
{{- if .tls }}
  tls:
  - hosts:
    - {{ .name }}
    {{ if eq (default .tlsType "auto") "auto" }}
    secretName: {{ .name | replace "." "-" }}-autogen
    {{- else if .tlsCustom }}
    secretName: {{ .tlsCustom }}
    {{- end }}
{{- end }}
---
{{- end }}
{{- end }}
