image:
  repository: iqualch/dc-drupal
  tag: latest
  pullPolicy: Always
  pullSecrets:
    - iqual-docker-cloud

autoInstall:
  enabled: false
  baseMount: /mnt/local
  source: /repo
  file: ""
  dbHost: master-db
  dbSecret: master-db-access

ingress:
  enabled: false
  certissuer: "letsencrypt-prod"
  hosts:
  - name: drupal.local
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/proxy-body-size: 100M
      nginx.ingress.kubernetes.io/proxy-buffer-size: 16K
    tls: true
    tlsType: "auto"

persistence:
  enabled: true
  baseMount: /mnt/local

nodeSelection:
  enabled: false
  selector: {}
