image:
  repository: iqualch/dc-drupal
  tag: latest
  pullPolicy: Always
  pullSecrets:
    - iqual-docker-cloud

iqapi:
  enabled: false
  wid: ""
  endpoint: ""
  token: ""

autoInstall:
  enabled: false
  baseMount: /mnt/dummy_volume
  source: /repo
  file: ""
  dbHost: master-db
  dbSecret: master-db-access

ingress:
  enabled: false
  certissuer: "letsencrypt-prod"
  hosts:
  - name: drupal.local
    annotations:
      kubernetes.io/ingress.class: nginx
    tls: true
    tlsType: default
    tlsCustom: cluster-default

persistence:
  enabled: true
  baseMount: /mnt/dummy_volume

nodeSelector: {}
