image:
  repository: iqualch/dc-drupal
  tag: nginx-php7.3
  pullPolicy: Always
  pullSecrets:
    - iqual-docker-cloud

ingress:
  enabled: false
  certissuer: "letsencrypt-prod"
  defaultAnnotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 100M
    nginx.ingress.kubernetes.io/proxy-buffer-size: 16K
  hosts:
  - name: drupal.local
    annotations:
      kubernetes.io/ingress.class: nginx
    tls: true
    tlsType: "auto"

persistence:
  enabled: true
  baseMount: /mnt/local

resources:
  requests:
    memory: 100Mi

nodeSelection:
  enabled: false
  selector: {}
